# Generated by Django 6.1.1 on 2026-09-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='previous_rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
