# Generated by Django 6.1.1 on 2026-09-30 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_previous_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='previous_rank',
        ),
        migrations.CreateModel(
            name='ChartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('chart_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_history', to='music.song')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('song', 'chart_date')},
            },
        ),
    ]
